services:
  eventmanager:
    build:
      context: ../eventmanager
      dockerfile: Dockerfile
    container_name: eventmanager
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://eventmanager-db:5432/eventmanager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - eventmanager-db
      - kafka
      - kafka-2
      - kafka-3
    networks:
      - event-net
    restart: unless-stopped

  eventmanager-db:
    image: postgres:15
    container_name: eventmanager-db
    restart: always
    environment:
      POSTGRES_DB: eventmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - eventmanager-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - event-net

  event-notificator:
    build:
      context: ../event-notificator
      dockerfile: Dockerfile
    container_name: event-notificator
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://event-notificator-db:5432/eventnotificator
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    restart: unless-stopped
    depends_on:
      - event-notificator-db
      - kafka
      - kafka-2
      - kafka-3
    networks:
      - event-net

  event-notificator-db:
    image: postgres:15
    container_name: event-notificator-db
    restart: always
    environment:
      POSTGRES_DB: eventnotificator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - eventnotificator-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - event-net

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    restart: unless-stopped
    networks:
      event-net:

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    restart: unless-stopped
    networks:
      event-net:

  kafka-2:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-2
    depends_on:
      - zookeeper
    ports:
      - "29093:29093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9093,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      restart: unless-stopped
    networks:
      - event-net

  kafka-3:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-3
    depends_on:
      - zookeeper
    ports:
      - "29094:29094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9094,PLAINTEXT_HOST://localhost:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      restart: unless-stopped
    networks:
      - event-net

volumes:
  eventmanager-data:
  eventnotificator-data:

networks:
  event-net:
    driver: bridge
