server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      auto-create: true

  application:
    name: eventmanager
  liquibase:
    enabled: true
    change-log: db/changelog/master.xml
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      max-lifetime: 1_800_000
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true


logging:
  level:
    root: info
    com.lostway.eventmanager.aop: info
springdoc:
  swagger-ui:
    url: /openapi.yaml
secret.key: verylongsecretkeyforpetprojecteventmanagerlostway2025

#In second
expiration.time: 3600

scheduler:
  cron: 0 * * * * *