spring:
  application:
    name: eventmanager
  liquibase:
    enabled: true
    change-log: db/changelog/master.xml
  datasource:
    url: jdbc:postgresql://localhost:5433/eventmanagerdb
    username: postgres
    password: pass
    hikari:
      max-lifetime: 1_800_000
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

logging:
  level:
    root: info
    com.lostway.eventmanager.controller: info
    com.lostway.eventmanager.service: debug
springdoc:
  swagger-ui:
    url: /openapi.yaml
secret.key: verylongsecretkeyforpetproject