server:
  port: 8081

spring:
  application:
    name: eventmanager
  profiles:
    active: docker

  kafka:
    producer:
      retries: 3
      acks: all
    admin:
      auto-create: true

  liquibase:
    enabled: true
    change-log: db/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  datasource:
    hikari:
      max-lifetime: 300000
      maximum-pool-size: 20

logging:
  level:
    root: info
    com.lostway.eventmanager.aop: info
springdoc:
  swagger-ui:
    url: /openapi.yaml
secret.key: verylongsecretkeyforpetprojecteventmanagerlostway2025

#In second
expiration.time: 3600

scheduler:
  cron: 0 * * * * *