spring:
  kafka:
    bootstrap-servers: kafka:9092, kafka-2:9093, kafka-3:9094
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}